version: 1

values: {}

targets:
  proxy:
    values:
      grade: production
      memory:
        initial: 1G
        max: 1G
  survival:
    values:
      memory:
        initial: 4096M
        max: 8192M
  creative:
    values:
      memory:
        initial: 1024M
        max: 2048M
