version: 1

values: {}

targets:
  proxy:
    values:
      grade: staging
      memory:
        initial: 256M
        max: 256M
  survival:
    values:
      memory:
        initial: 2048M
        max: 2048M

