version: 1

values:
  motd: "A gok powered Minecraft server! <yellow>(Staging)"

targets:
  proxy:
    values:
      memory:
        initial: 256M
        max: 256M
  survival:
    values:
      memory:
        initial: 2048M
        max: 2048M

