realm:
    velocity:
        #ENC[AES256_GCM,data:bJtnl9vYQRXsKYG3ODa/oWlUcv4dqBcfjE9mhLVWFp9F1Tf8nUjKrWcFjzVTZUXj+DJvq69Fjj7GPmK9AiP4sTJfC6KuK237ApfYnVdA,iv:7IVuc+OqSvjOV0jx9r5QAdZ3Ola3Hj8pLz5EpHL5HlY=,tag:Tv2OLzg7nKHzt2PxZR1lyQ==,type:comment]
        forwarding_secret: ENC[AES256_GCM,data:P/0R3bqLnXkOGwpzohPQqJMK,iv:+R+SvX+dBzWGqMqYbqZsR9Hsc088+3b5IDil+Y2ZCjk=,tag:NtRufxaUYUzQf3M5hEzMdw==,type:str]
    databases:
        redis:
            host: ENC[AES256_GCM,data:BT/UJFaqHuKB,iv:IY8sGVr2j8UYjfycXmNz6YcpuUKdta78YIUxa9T7obs=,tag:lS/91yeLWJknySsfo6qRFQ==,type:str]
            port: ENC[AES256_GCM,data:+UvnrQ==,iv:bpGy0T1pdqwHCL0N+gEr9BHzRVMgkWyyQ1M6hJ6vVFs=,tag:WUHCQupGTWpLLoh/CBc+AA==,type:int]
            password: ENC[AES256_GCM,data:7id0uLSucp6XbE1p+2M2feBFyA==,iv:dta/Xigj69nv2rekZPqEKL8pKQq+37Dlu+138mNUt/A=,tag:TRTkXq/KQrzEt3EcjBC5bQ==,type:str]
        postgres:
            host: ENC[AES256_GCM,data:lpJ2apSyH5Uh,iv:TmPGXoTqlADQgd0MGCh6/LhP1q1nd94jIc83fuKUEYY=,tag:L9PcyRzOi3Rz542cBKWbew==,type:str]
            port: ENC[AES256_GCM,data:lzEFCg==,iv:P7RAXng9x/Cm7UbwokzJFh4FUNmmyYuUBqG2e72ElaQ=,tag:ITf7wGpKE09mv+w1r5ZmTA==,type:int]
            username: ENC[AES256_GCM,data:RjM6OA==,iv:TZ4a1VhOkyKt6/AxKx3P3qOfxmumBqH6+a1ZkD93TvA=,tag:dnfQdG378ye4GSrr3CI0xw==,type:str]
            password: ENC[AES256_GCM,data:m95GiA3D,iv:M5Rzbodt70LkfnK9D4eg06yQzuBm9nOOqSJWT8MIwyc=,tag:mKMDSQFKRsdI2A12pLN4tQ==,type:str]
sops:
    age:
        - recipient: age1lz4ypl8k6uekdpxs5y0zkhhyw5zse4sjdtmu9ex3gfyuln3gde0q82keal
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdFg0KzFqT1A1bkJ2SXJV
            VWJUWTl5SlBHTVgrRS9FTWZKTUVkUDBSa0RrCjd5Sm91ZStobDhpczlvT3pTMHdi
            TDJpcHJoL2FpWVVveXRCRGFpMlNreGsKLS0tIFVZQ3dlYi9ZR3c3NytDYXhOUTI2
            MitETzljcFdzUU9jcmVJbGV6ckk0TGcKg6ia1pPqa0xQ6ogKxuwG3CZL1Gpi0Yyh
            bTCrPSf2ELyr1rAp5ormhLHB77UY4Hf8a+DEtlYQEObx5dGwQhHx0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHTDNhZmC9CDyU8/tClLN1vlaSUT8iie1yMpRTvHRy19 tom.romeo.doil@gmail.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFVPcW83QSB5OTFN
            UWVMdDY2SGg2UnJPbW9JOWREUGxnQUdvL3pjTy9BZUVtMkVINVNFClR3cHFGZFlz
            eXhYWElQNmQySXdxb0hGNENhajVRTWJWb2M1NnpaenJxODAKLS0tIG1TSVpOVkh4
            bEVnYWwwN3RTZUtnQjRDNWlZWDZNT0tERk5wV3lseWlndjQKZCX7pp4UOD3c1dk8
            N6tidMm2sJ4d+K0kTgbAF/uomKg6Hiw4rRdRqObJ3sxVZtkckFXCq8ARtYf5nqCx
            lFAWXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/ckWqOECfIplkWa7n+MvUWTH4C8+u07D79FLxq0fqNFIj1bPBh4nURxj3n7WXIpuXqo0xk3s8ubWiTX5kEEcJk1rsJmRk4iMYwrMG6tszTI9OULKLguifOjVI00DktsBh1srmhC9ZGDmEdPfDi6vknGwwSd6/7urX6xnmlHK+zK7zUBt5VidBmD3/1Cm7TVM5zrva4c3XeQxlNVHkkrR5RskkS1X7+S1F7mXHA21KCF66leDYUtlwg3zMB5FD04MTV+F44uBd23j4F1X2v8sk29GMbuiQ9SOmTScXDfl1hueL8bJKaScGmIPQuj4jVfnMDpDbz+3H88SNo0w36Pp0j/oIcBW/4CrxsfnLrgiJwwSf1XhlK0K/QDMcdahLHYr8dM3HL87B5Dx1o/KqlmyQF2w+jEopsPSm58ZU8twAtBsUWNR+y8Vc/D9WRq8Bh8RHdJN2N5Dvg8gqWUIjs3mec9ZTCz15uV9xWeT5wCyZmlH/dZYWQs07BvfpCmF1l1CyAxYyCGNYZ6N1hk/mY6uXWlhVFdgYq8pBHVyPurG4eTh0n1EoRrxbQ7VDX1kSrhAtDNjUdfBctNhN10ze7l9MGosSjIEFOK5dUJpoByjn7atzSn5FwEpJ5rZRxU9L1MGf49Ul7mGe3Hryp+yYPT425JFbUGHwe3tn3lNVRylgBQ==
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgdXFiU2pnCk1leEpybVFu
            SW9CdVlIdUU5ZUJGcm9oVkxucmI5OXZwN2hDQWNyMW4yc1RURm80aXhJcVpQcnVp
            YURKNjVzNGoKMFN5L2d1VUVWRE5ON1VlSGFnd2pXeHRMU3BaV0NsMTZyS0NDcjVH
            cDJvckl4VHVkUWkzNnJFeUJXNC9TejhzRQpDNERMeHd4YlVJVjBkNGRLVE5tdnlY
            bmRobGhKRWtDYk1taTlJdm5WUE8xa3p4MlFidm5YekcweUVDcUgwOXI3ClBkT1E4
            QlBBOFVYMGpHeERxNXdIZUVZa09MY2x1VzZwcjNCTmNFWit2WXFlZEI0K3YvT2Y4
            WVVseHlFSmhtYk0KTVNWbzM5UGJjVnpNNFdCbHpXdmtsc09GY2t6Q04wVVlOWm1j
            NHZFOEZPOHdhc0NQdlVXaFNFYmlqUTVJalVEVApmQnRjdzFrOHVEb2xhYitWeS9W
            cHpZTFVEWE1qOUJ5Y0JsYjIrRjhvNmkxalJzbmhyZnFGUWFUUW1XR1lTUVZlCnVH
            OTdVWFQ1WHNZM3BIeGJnREhpK0VaallDd1FsT1dtYmU4Tjg0QklvdzErNW1pUXRO
            dWxnUElIZEhERXpweXgKL3dxVURrUCthTEJ5N3pKYkF0ZXdNQi9HaVVhWmdxWUxF
            NnpxQld1Y0JPdWpsR1dhV0p5OE1OUktpZDdnMWRmSQp4d2VwYmNON0xLd2lndFBh
            cWVIT0x1QzIwV2RZMW9aaFJFa0Y3T0l0OXF1S0xWRUJsbjNqd1ZCbTU1VEZtVzhn
            CitNcnQ5NW9FWHBjT1NjQWpUWC9YT0YzdFZlYmZMYVVRNERkS0NsZm9ldlZ3MFdY
            cWxTalo2K0RKd2FrZGxDN0sKbHAxaFkwT1B6ejMwWm9uZitRNEx1RDJvYXpwV2Iy
            MnZ4Z2VCOFhjTWRUNAotLS0gNjNMU0hVd2dIcmZ0T2V5eVRBWDF3MndoK1dVQkdQ
            akdGdUhtMXRhSXJBYwpm30MTmqOLuWXWLhnbD/L5+A8BZO7yJKZ7uJS/S6PZiYwz
            gd733by5hnV1HgALPTXm4LGClgfZriTMngF8Aha+
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T10:20:28Z"
    mac: ENC[AES256_GCM,data:HvJz4zkaQIS5Wh5CSMXen2WqyRc11ldZakTYKNP5Oh2uA37XZmkcDUTy43mHUxj6z2OuFbHlBX3TaZ1QmoHbfeBRJ47d9d/eZ++j+49rf13b8MM/GwudYdHtdAs7/jO82Bk1ALLwltPuphAvRJFPj2AfLOz008P8o4JP8e99U0A=,iv:HEI1nF2W1zEhVTEv0Qh/w87hlArEfw1k5wztG+pKsds=,tag:7hKwuFUjTwDdwyStIZhSyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
